# Generated by Django 5.0.6 on 2024-07-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gadCampus',
            fields=[
                ('campId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('IsActive', models.CharField(default='Y', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='gadComponent',
            fields=[
                ('compId', models.AutoField(primary_key=True, serialize=False)),
                ('divId', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_component',
            },
        ),
        migrations.CreateModel(
            name='gadDivision',
            fields=[
                ('divId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_division',
            },
        ),
    ]
