# Generated by Django 5.0.6 on 2024-07-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashGADApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gadcampus',
            table='man_campus',
        ),
    ]
