# Generated by Django 5.0.6 on 2024-07-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashGADApp', '0003_gaddivision_campid'),
    ]

    operations = [
        migrations.CreateModel(
            name='gadDetails',
            fields=[
                ('gadId', models.AutoField(primary_key=True, serialize=False)),
                ('campId', models.CharField(max_length=20)),
                ('compId', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=150)),
                ('female', models.CharField(max_length=20)),
                ('male', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gad',
            },
        ),
    ]
