# Generated by Django 5.0.6 on 2024-06-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stratArea',
            fields=[
                ('areaId', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=250)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_strat_area',
            },
        ),
        migrations.CreateModel(
            name='stratIndicator',
            fields=[
                ('indId', models.AutoField(primary_key=True, serialize=False)),
                ('objId', models.CharField(max_length=20)),
                ('typeNo', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_strat_indicator',
            },
        ),
        migrations.CreateModel(
            name='stratObjective',
            fields=[
                ('objId', models.AutoField(primary_key=True, serialize=False)),
                ('areaId', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'man_strat_objective',
            },
        ),
    ]
