# Generated by Django 5.0.6 on 2024-06-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashStrategicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stratPlanMatrices',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('indId', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=20)),
                ('blineData', models.CharField(max_length=30)),
                ('targetPlan', models.CharField(max_length=30)),
                ('yr2022', models.CharField(max_length=20)),
                ('yr2023', models.CharField(max_length=20)),
                ('yr2024', models.CharField(max_length=20)),
                ('yr2025', models.CharField(max_length=20)),
                ('yr2026', models.CharField(max_length=20)),
                ('yr2027', models.CharField(max_length=20)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'strat_plan_matices',
            },
        ),
    ]
