# Generated by Django 5.0.6 on 2024-06-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashStrategicApp', '0002_stratplanmatrices'),
    ]

    operations = [
        migrations.CreateModel(
            name='stratYearlyScorecard',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('indId', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=30)),
                ('target', models.CharField(max_length=20)),
                ('actual', models.CharField(max_length=20)),
                ('variance', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=20)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'strat_yearly_scorecard',
            },
        ),
    ]
