# Generated by Django 5.0.6 on 2024-08-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashStrategicApp', '0004_strattemplate_strattemplatedet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strattemplatedet',
            name='year',
        ),
    ]
