# Generated by Django 5.0.6 on 2024-09-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashStrategicApp', '0005_remove_strattemplatedet_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='stratReference',
            fields=[
                ('refNo', models.AutoField(primary_key=True, serialize=False)),
                ('refName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'ref_strat_reference',
            },
        ),
    ]
