# Generated by Django 5.0.6 on 2024-05-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analIndicator',
            fields=[
                ('analIndId', models.AutoField(primary_key=True, serialize=False)),
                ('analId', models.CharField(max_length=20)),
                ('colDescription', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'anal_indicator',
            },
        ),
        migrations.CreateModel(
            name='analIndicatorDet',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('analIndId', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'anal_indicator_det',
            },
        ),
        migrations.CreateModel(
            name='analPrograms',
            fields=[
                ('progId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'anal_program',
            },
        ),
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('analId', models.AutoField(primary_key=True, serialize=False)),
                ('progId', models.CharField(default='', max_length=20)),
                ('typeNo', models.CharField(max_length=20)),
                ('indicator', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'analytics',
            },
        ),
        migrations.CreateModel(
            name='refType',
            fields=[
                ('typeNo', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'ref_type',
            },
        ),
    ]
