# Generated by Django 5.0.6 on 2024-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAnalyticApp', '0004_analaccreditation'),
    ]

    operations = [
        migrations.CreateModel(
            name='analGradResearch',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('analId', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('noOfGradFac', models.CharField(max_length=100)),
                ('noOfGradFacRes', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'anal_grad_research',
            },
        ),
    ]
