# Generated by Django 5.0.6 on 2024-06-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAnalyticApp', '0005_analgradresearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='analResDegree',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('analId', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('noOfGrad', models.CharField(max_length=100)),
                ('noOfGradResDeg', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'anal_res_degree',
            },
        ),
    ]
