# Generated by Django 5.0.6 on 2024-06-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAnalyticApp', '0006_analresdegree'),
    ]

    operations = [
        migrations.CreateModel(
            name='analAccGradProg',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('analId', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('noOfGradProg', models.CharField(max_length=100)),
                ('noOfAccrGradProg', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'anal_accr_grad_prog',
            },
        ),
    ]
