# Generated by Django 5.0.6 on 2024-06-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAnalyticApp', '0012_analtrainees'),
    ]

    operations = [
        migrations.CreateModel(
            name='analExtProgram',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('analId', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('noOfExtProgram', models.CharField(max_length=100)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'anal_ext_program',
            },
        ),
        migrations.RenameField(
            model_name='analtrainees',
            old_name='noOfTrainess',
            new_name='noOfTrainees',
        ),
    ]
