# Generated by Django 5.0.6 on 2024-06-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashAnalyticApp', '0013_analextprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='analBeneficiaries',
            fields=[
                ('ctrlNo', models.AutoField(primary_key=True, serialize=False)),
                ('analId', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('noOfBenef', models.CharField(max_length=100)),
                ('noOfBenefRate', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'anal_beneficiaries',
            },
        ),
    ]
