# Generated by Django 5.0.6 on 2024-05-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ludip',
            fields=[
                ('ludipId', models.AutoField(primary_key=True, serialize=False)),
                ('campus', models.CharField(default='', max_length=100)),
                ('totalLandArea', models.CharField(max_length=50)),
                ('landUsed', models.CharField(max_length=50)),
                ('remainLand', models.CharField(max_length=50)),
                ('landUsedMap', models.CharField(max_length=250)),
                ('siteDevPlan', models.CharField(max_length=250)),
                ('remarks', models.CharField(max_length=500)),
                ('isActive', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'ludip',
            },
        ),
    ]
